name: Build and deploy to dev

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "CODEOWNERS"
    branches:
      - "**"

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: |
      github.ref_name == 'main' ||
      contains(github.event.head_commit.message, 'deploy:dev') ||
      github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      id-token: write
      actions: read
      packages: read
    steps:
      - uses: actions/checkout@v4

      - name: Push Docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: arbeidsplassen
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          docker_context: .
          build_secrets: npm_auth_token=${{ secrets.READER_TOKEN }}

      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev.yaml
          VAR: image=${{ steps.docker-build-push.outputs.image }}
